basePath: /
definitions:
  models.Student:
    properties:
      age:
        type: integer
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API cho hệ thống quản lý sinh viên với Redis cache
  title: Student Service API
  version: "1.0"
paths:
  /students:
    post:
      consumes:
      - application/json
      description: Create a new student in the system
      parameters:
      - description: Student Information
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
      summary: Create a new student
  /students/{id}:
    delete:
      description: Delete a student in the system
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Student deleted successfully
          schema:
            type: string
      summary: Delete a student by ID
    get:
      description: Get a student by ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
      summary: Get a student by ID
    put:
      consumes:
      - application/json
      description: Update a student in the system
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated Student Information
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
      summary: Update a student by ID
swagger: "2.0"
